-- FirstSignal Sim v1 durable thought storage.
-- The physical table name gcdt_thoughts is retained for backward compatibility.
create table if not exists public.gcdt_thoughts (
  id bigint generated by default as identity primary key,
  session_id text not null,
  market_time text,
  kind text not null default 'thought',
  content text not null,
  decision text,
  spot numeric,
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

create index if not exists gcdt_thoughts_created_at_idx
  on public.gcdt_thoughts (created_at desc);

create index if not exists gcdt_thoughts_session_idx
  on public.gcdt_thoughts (session_id, created_at);

alter table public.gcdt_thoughts enable row level security;

-- The Vercel server route uses a server-side key.
-- Do not expose a service-role key through a VITE_ environment variable.

