const $=id=>document.getElementById(id);const esc=v=>String(v??'').replace(/[&<>"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;'}[c]));
function color(s){if(String(s).includes('APPROVAL'))return'#ff4060';if(String(s).includes('MEETING')||String(s).includes('STARTING'))return'#f0c040';return'#00d4a8'}
function render(d){const sup=d.supervisor||{},state=sup.state||d.status?.state||'UNKNOWN',c=color(state);$('status').textContent=state;$('status').style.color=c;$('dot').style.background=c;$('folder').textContent=`Saves to: ${d.settings?.reportFolder||'Not configured'}`;
const camp=sup.campaign;$('campaignStatus').textContent=camp?`${camp.name} | ${camp.completedRuns||0}/${camp.targetRuns} complete | ${camp.status}`:'No campaign running';
$('proposals').innerHTML=camp?.proposals?.length?camp.proposals.map((p,i)=>`<div class="card ${String(p.severity||'yellow').toLowerCase()}"><div class="meta">${esc(p.severity)} | ${esc(p.category)} | ${esc(p.observedIn)} | risk ${esc(p.risk)} | ${esc(p.approvalStatus)}</div><div class="title">${i+1}. ${esc(p.title)}</div><div class="summary"><b>Why:</b> ${esc(p.why)}<br><b>Proposed:</b> ${esc(p.proposedAction)}</div><div class="proposal-actions"><button onclick="decideProposal(${i},'approve')">Approve</button><button onclick="decideProposal(${i},'reject')">Reject</button></div></div>`).join(''):'<div class="panel meta">The consolidated approval list appears after the requested simulations and meetings finish.</div>';
const m=d.meeting||{};$('meetingStatus').textContent=`${m.state||'IDLE'}${m.name?` · ${m.name}`:''}`;$('startMeeting').disabled=d.status?.state!=='COMPLETED'||['RUNNING','STOPPING','PAUSED_RATE_LIMIT'].includes(m.state);$('stopMeeting').disabled=!['RUNNING','PAUSED_RATE_LIMIT'].includes(m.state);$('openMeeting').disabled=!m.folder;
$('activity').innerHTML=[...(d.activities||[])].reverse().slice(0,30).map(a=>`<div class="activity-line"><b>${esc(a.kind)}</b> | ${esc(a.message)}</div>`).join('')||'<div class="meta">Waiting for activity...</div>';
$('reports').innerHTML=[...(d.reports||[])].reverse().map(r=>`<div class="card ${String(r.level||'green').toLowerCase()}"><div class="meta">${esc(r.level)} | ${esc(r.category)} | ${esc(r.buildId)}</div><div class="title">${esc(r.title)}</div><div class="summary">${esc(r.summary)}</div></div>`).join('')||'<div class="panel meta">No findings yet.</div>'}
async function refresh(){try{const r=await fetch('http://127.0.0.1:8766/status');render(await r.json())}catch{ $('status').textContent='OFFLINE'}}setInterval(refresh,1000);refresh();
$('startCampaign').onclick=async()=>{const runs=Number($('campaignRuns').value||1),replayDates=$('campaignDates').value.split(',').map(x=>x.trim()).filter(Boolean);const r=await fetch('http://127.0.0.1:8766/supervisor/campaign',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({runs,replayDates})});if(!r.ok)alert((await r.json().catch(()=>({}))).error||'Unable to start campaign');};
window.decideProposal=(index,decision)=>fetch('http://127.0.0.1:8766/supervisor/proposal/decision',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({index,decision})});
$('startMeeting').onclick=()=>fetch('http://127.0.0.1:8766/meeting/start',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({name:$('meetingName').value.trim()})});$('stopMeeting').onclick=()=>fetch('http://127.0.0.1:8766/meeting/stop',{method:'POST'});$('openMeeting').onclick=()=>fetch('http://127.0.0.1:8766/meeting/open',{method:'POST'});
$('openFolder').onclick=()=>window.agentConsole.openFolder();$('openNotebook').onclick=()=>window.agentConsole.openNotebook();$('changeFolder').onclick=()=>window.agentConsole.chooseFolder();